; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "Apprend tes dates"
#define MyAppVersion "1.0"
#define MyAppPublisher "Henry Letellier"
#define MyAppURL "https://www.github.com/HenraL"

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{0923843B-1D61-498F-BC70-0F551EDDA586}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={autopf}\{#MyAppName}
DefaultGroupName={#MyAppName}
; Uncomment the following line to run in non administrative install mode (install for current user only.)
;PrivilegesRequired=lowest
PrivilegesRequiredOverridesAllowed=dialog
OutputDir=C:\Users\Henry PC\Dropbox\Henry et Papa\Matières\NSI\T1\Dates d'histoire\outputfolder\firstexetest
OutputBaseFilename=learndatessetup
SetupIconFile=C:\Program Files (x86)\Apprend tes dates\py.ico
Compression=lzma
SolidCompression=yes
WizardStyle=modern

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"
Name: "french"; MessagesFile: "compiler:Languages\French.isl"

[Files]
Source: "C:\Program Files (x86)\Apprend tes dates\Download Python.url"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Program Files (x86)\Apprend tes dates\py.ico"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Program Files (x86)\Apprend tes dates\README.txt"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Program Files (x86)\Apprend tes dates\see your stats.txt"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Program Files (x86)\Apprend tes dates\startersoft.bat"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Program Files (x86)\Apprend tes dates\Stats_dates_d_histoire_Graphic_py.txt"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Program Files (x86)\Apprend tes dates\prog\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "C:\ProgramData\Microsoft\Windows\Start Menu\Programs\Apprend tes dates\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Icons]
Name: "{group}\{cm:UninstallProgram,{#MyAppName}}"; Filename: "{uninstallexe}"

