dates=[
    {"date":"A binder","event":"A class folder binding loose paper"},
    {"date":"A report","event":"Un compte rendu"},
    {"date":"All Saints Vacation","event":"la toussain"},
    {"date":"A placement test","event":"un test de niveau"},
    {"date":"To be unveiled","event":"To be revealed/inaugurated"},
    {"date":"To topple a monument","event":"To destroy/break a monument"},
    {"date":"The flip of the coin","event":"the second side/the bad aspect"},
    {"date":"Wisdom teeth","event":"Dent de sagesse"},
    {"date":"A key question","event":"Une problématique"},
    {"date":"Consumer society","event":"La société de consommation"},
    {"date":"A minstrel","event":"Un ministrel"},
    {"date":"A tomboy","event":"Un garçon manqué"},
    {"date":"Whom","event":"The person whom I wanted to see was absent"},
    {"date":"Who","event":"The person who was in the restaurant was nice"},
    {"date":"A competitive exam","event":"Un examen"},
    {"date":"Ephemeral art","event":"Temporary"},
    {"date":"To bounce","event":"Rebondir"},
    {"date":"To adhere","event":"To agree"},
    {"date":"Strength","event":"Force"},
    {"date":"College","event":"1st 4 years of University"},
    {"date":"Collège","event":"Junior high (school)"},
    {"date":"Lycée","event":"Senior high (School)"},
    {"date":"PhD","event":"Doctora"},
    ]
